CREATE TABLE tuser(
	id INT PRIMARY KEY AUTO_INCREMENT,
	nama VARCHAR(255),
	jenis_kelamin VARCHAR(100),
	ttl VARCHAR(250),
	nim VARCHAR(50),
	ipk DOUBLE,
	jurusan VARCHAR(200),
	univ TEXT,
	tahun_masuk INTEGER,
	nomor_rekening VARCHAR(255),
	nomor_hp VARCHAR(200),
	ket TEXT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
